# Generated by Django 5.1.7 on 2025-04-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_alter_myadmin_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='myadmin',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
