# Generated by Django 5.1.7 on 2025-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_myadmin_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('social', 'Social'), ('education', 'Education')], max_length=20)),
                ('first', models.TextField()),
                ('second', models.TextField()),
                ('conclusion', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
    ]
