# Generated by Django 5.2 on 2025-05-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urmilafoundation', '0003_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='otp_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
